[project]
authors = [{ name = "Maximilian Kruse", email = "maxkruse1604@gmail.com" }]
maintainers = [{ name = "Maximilian Kruse", email = "maxkruse1604@gmail.com" }]
description = "Universal Coordinates for the Left Atrium "
name = "ulac"
requires-python = ">=3.13"
dynamic = ["version"]
readme = "README.md"
license = { text = "MIT" }
keywords = [""]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
]


# --------------------------------------------------------------------------------------------------
dependencies = [
    "fast-simplification>=0.1.13",
    "h5py>=3.16.0",
    "igraph>=1.0.0",
    "libigl>=2.6.1",
    "msgspec>=0.20.0",
    "networkx>=3.6.1",
    "numba>=0.62.1",
    "numpy>=2.3.4",
    "python-igraph>=1.0.0",
    "pyvista[all]==0.46.4",
    "trimesh>=4.9.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.2",
]
examples = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "trame>=3.12.0",
    "trame-vtk>=2.10.0",
    "trame-vuetify>=3.1.0",
    "trame-server<3.7",
    "meshlib>=3.1.1.92",
]


# --------------------------------------------------------------------------------------------------
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.uv]
environments = ["sys_platform == 'linux'"]
cache-keys = [
  { file = "pyproject.toml" },
  { git = { commit = true, tags = true } },
]
default-groups = []


# --------------------------------------------------------------------------------------------------
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812",
  "EM101",
  "EM102",
  "FBT001",
  "FBT003",
  "F722",
  "F821",
  "ISC001",
  "PD008",
  "PD011",
  "PLR2004",
  "PT003",
  "RET504",
  "S101",
  "TRY003",
]
per-file-ignores = { "test/*" = ["ANN001", "ANN201", "D100", "D103", "D104", "INP001", "SLF001"] }
pydocstyle.convention = "google"


# --------------------------------------------------------------------------------------------------
[tool.pytest.ini_options]
testpaths = ["test"]
addopts = [
  "-v",
  "--import-mode=importlib",
  "--cov=ulac",
  "--cov-config=.coveragerc",
]
markers = [
  "unit: unit tests",
  "integration: integration tests",
  "compile: requires compilation",
  "slow: tests with long runtime",
]
